DATA_SEG  SEGMENT
COL EQU 7 ;Num OF COLUMNS
ROW EQU 4 ;Num OF ROWS
SUM DB ?
TAB_C DB 7 DUP(?) ;TABLE USED FOR COL-REDUCTION
matrix DB 1 ,1 ,0 ,1 ,0 ,0 ,1  
        DB 0 ,1 ,0 ,1 ,1 ,0 ,0
        DB 1 ,0 ,0 ,0 ,1 ,1 ,0 
        DB 0 ,1 ,0 ,1 ,0 ,0 ,1 
        
TAB_ASCII DB  '0123456789' 
          DB  'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
          DB  'abcdefghijklmnopqrstuvwxyz'
          DB  ' !\"#$%&''()*+,-./:;<=>?@[\\]^_`{|}~' ;REDUCED ASCII TABLE
  
DATA_SEG ENDS

PILE SEGMENT STACK
FRAME DW 256 DUP(?) 
TOP LABEL WORD
PILE ENDS

CODE_SEG  SEGMENT
    ASSUME CS:CODE_SEG, DS: DATA_SEG, SS: PILE
    
COLUMN_REDUCTION PROC
    MOV AX,DATA_SEG
    MOV DS,AX
    XOR DI,DI ;SETTING DESTINATION INDEX REG TO 0
    MOV CX,COL
    LEA BX,TAB_ASCII ;ACCES TO A REDUCED ASCII TABLE TO CONVERT RESULTS 
                        ;INTO READABLE DATA
TAB:
    MOV SI,DI ;SI AND DI ARE POINTING TO THE SAME 1:J ELEMENT EVERY 
                ;START OF CALCULATION OF SUM
    MOV SUM,0
    MOV DX,ROW  ;USING DX AS A COUNTER
SUMM:
    MOV AL,matrix[SI] 
    ADD SUM,AL
    ADD SI,COL ;EVERY ELEMENT IN THE SAME COLUMN-DIFFERENT ROW ARE PLACED
                ;EXACTELY ONE COLUMN (7 CASES) AWAY FROM EACH OTHER
    DEC DX
    CMP DX,0
    JNZ SUMM
    MOV AL,SUM
    xlat ;CONVERSION NEEDED INSTRUCTION
    MOV TAB_C[DI],AL
    INC DI
    
    LOOP TAB
   
    ;IN PRINT STEP,WE'LL BE USING THE FUNCTION 09H/10H AND NEED 
    ;FOLLOWING REGESTERS FOR:
   MOV CX,COL ;COUNTER: Num OF CHARS
   MOV SI,OFFSET TAB_C  ;ACCES TO CHAR
   
PRINT:
   LODSB ;INSTRUCTION TO LOAD THE NEXT BYTE IN SI TO AL
   MOV AH,09H ;FUNCTION Num
   MOV BH,0 ;PAGE Num
   MOV BL,0EH ;COLOR: YELLOW
   INT 10H
   LOOP PRINT
 
    RET
COLUMN_REDUCTION ENDP

START:
    MOV AX,PILE
    MOV SS,AX
    LEA SP,TOP
    CALL COLUMN_REDUCTION
  
    MOV AX,4C00H
    INT 21H
  
    
    
   
CODE_SEG ENDS
    END START
           
    
    
           
