COLUMN_REDUCTION PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH SI
    PUSH DI
    XOR DI, DI ;SETTING DESTINATION INDEX REG TO 0
    MOV CX, COLS
    LEA BX, TAB_ASCII ;ACCES TO A REDUCED ASCII TABLE TO CONVERT RESULTS 
TAB:
    MOV SI, DI ;SI AND DI ARE POINTING TO THE SAME 1:J ELEMENT EVERY 
    MOV SUM, 0
    MOV DX, ROWS  ;USING DX AS A COUNTER
SUMM:
    MOV AL, matrix[SI] 
    SUB AL, '0'  ; Convert char to number
    ADD SUM, AL
    ADD SI, COLS ;EVERY ELEMENT IN THE SAME COLUMN-DIFFERENT ROW ARE PLACED
    DEC DX
    CMP DX, 0
    JNZ SUMM
    MOV AL, SUM
    XLAT ;CONVERSION NEEDED INSTRUCTION
    MOV TAB_C[DI], AL
    INC DI
    LOOP TAB
    ;IN PRINT STEP,WE'LL BE USING THE FUNCTION 09H/10H AND NEED 
    ;FOLLOWING REGESTERS FOR:
    MOV CX, COLS ;COUNTER: Num OF CHARS
    LEA SI, TAB_C  ;ACCES TO CHAR
PRINT:
    LODSB ;INSTRUCTION TO LOAD THE NEXT BYTE IN SI TO AL
    MOV AH, 09H ;FUNCTION Num
    MOV BH, 0 ;PAGE Num
    MOV BL, 0EH ;COLOR: YELLOW
    INT 10H
    LOOP PRINT
    POP DI
    POP SI
    POP DX
    POP CX
    POP BX
    POP AX
    RET
COLUMN_REDUCTION ENDP
           
    
    
    