COLUMN_REDUCTION PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH SI
    PUSH DI
    
    XOR DI, DI              ; INDEX FOR RESULT ARRAY
    MOV CX, COLS            ; LOOP COUNTER FOR COLUMNS
    LEA BX, TAB_ASCII       ; LOOKUP TABLE FOR CONVERSION
    
; ===== CALCULATE COLUMN SUMS =====
CALC_LOOP:
    MOV SI, DI              ; STARTING POSITION FOR COLUMN
    MOV SUM, 0              ; RESET SUM
    MOV DX, ROWS            ; ROW COUNTER
    
SUM_LOOP:
    MOV AL, matrix[SI]
    SUB AL, '0'             ; CONVERT ASCII CHAR TO NUMBER
    ADD SUM, AL             ; ADD TO COLUMN SUM
    ADD SI, COLS            ; MOVE TO NEXT ROW IN SAME COLUMN
    DEC DX
    JNZ SUM_LOOP
    
    MOV AL, SUM
    XLAT                    ; CONVERT NUMBER TO ASCII USING TABLE
    MOV TAB_C[DI], AL       ; STORE CONVERTED CHARACTER
    INC DI
    LOOP CALC_LOOP
    
; ===== DISPLAY RESULTS IN YELLOW USING INT 10H AH=09H =====
    MOV CX, COLS            ; RESET COUNTER FOR DISPLAY
    XOR SI, SI              ; RESET INDEX FOR TAB_C

DISPLAY_LOOP:
    PUSH CX
    MOV AL, TAB_C[SI]       ; LOAD CHARACTER FROM RESULT ARRAY
    MOV AH, 09H             ; INT 10H: WRITE CHAR + ATTRIBUTE AT CURSOR
    MOV BH, 0               ; PAGE 0
    MOV BL, 0EH             ; YELLOW ATTRIBUTE
    MOV CX, 1               ; PRINT 1 TIME
    INT 10H                 ; OUTPUT CHARACTER WITH COLOR
    ; ADVANCE CURSOR AFTER CHARACTER
    MOV AH, 03H
    MOV BH, 0
    INT 10H                 ; READ CURSOR -> DH=ROW, DL=COL
    INC DL
    MOV AH, 02H
    MOV BH, 0
    INT 10H                 ; SET NEW CURSOR POSITION
    ; PRINT SPACE SEPARATOR IN YELLOW
    MOV AH, 09H
    MOV AL, ' '
    MOV BH, 0
    MOV BL, 0EH             ; YELLOW
    MOV CX, 1
    INT 10H
    ; ADVANCE CURSOR AFTER SPACE
    MOV AH, 03H
    MOV BH, 0
    INT 10H
    INC DL
    MOV AH, 02H
    MOV BH, 0
    INT 10H
    POP CX
    INC SI                  ; NEXT COLUMN RESULT
    LOOP DISPLAY_LOOP       ; DECREMENT CX AND REPEAT

    ; MOVE CURSOR TO START OF NEXT LINE
    MOV AH, 03H
    MOV BH, 0
    INT 10H                 ; READ CURSOR -> DH=ROW, DL=COL
    INC DH                  ; NEXT ROW
    MOV DL, 0               ; COLUMN 0
    MOV AH, 02H
    MOV BH, 0
    INT 10H                 ; SET CURSOR TO START OF NEXT ROW
    
    POP DI
    POP SI
    POP DX
    POP CX
    POP BX
    POP AX
    RET
COLUMN_REDUCTION ENDP